-- AlterTable
ALTER TABLE `OffboardingChangeLog` MODIFY `action` ENUM('CREATED', 'UPDATED', 'DELETED', 'RESTORED', 'REVERTED', 'CANCELLED', 'MAIL_SENT', 'MAIL_ENQUEUED', 'MAIL_FAILED', 'STATUS_CHANGED', 'PROBATION_REMINDER_SENT', 'PROBATION_EVALUATION_SENT', 'NOTICE_REMINDER_SENT') NOT NULL;

-- AlterTable
ALTER TABLE `OnboardingChangeLog` MODIFY `action` ENUM('CREATED', 'UPDATED', 'DELETED', 'RESTORED', 'REVERTED', 'CANCELLED', 'MAIL_SENT', 'MAIL_ENQUEUED', 'MAIL_FAILED', 'STATUS_CHANGED', 'PROBATION_REMINDER_SENT', 'PROBATION_EVALUATION_SENT', 'NOTICE_REMINDER_SENT') NOT NULL;
