-- AlterTable
ALTER TABLE `EmailHistory` ADD COLUMN `changeId` INTEGER NULL,
    MODIFY `emailType` ENUM('EMPLOYEE_INFO', 'MONTHLY_SUMMARY', 'PROBATION_WARNING', 'PROBATION_REMINDER', 'PROBATION_ENDING', 'PROBATION_EVALUATION_LINK', 'PROBATION_MISSING_EMAIL', 'PROBATION_SUBMITTED', 'PROBATION_FORM_COMPLETED', 'PROBATION_SUPERVISOR_21_DAYS', 'PROBATION_HR_INFO_21_DAYS', 'PROBATION_HR_REMINDER_1_DAY', 'PROBATION_COMPLETED', 'PROBATION_MISSING_SUPERVISOR', 'NOTICE_WARNING', 'NOTICE_ENDING', 'SIGNATURE_INVITE', 'EXIT_CHECKLIST_SIGNATURE_INVITE', 'EXIT_SIGNATURE_INVITE', 'BEHALF_SIGNATURE_INVITE', 'EXIT_CHECKLIST_BEHALF_SIGNATURE', 'HANDOVER_RECIPIENT', 'HANDOVER_RECIPIENT_INFO', 'EXIT_CHECKLIST_HANDOVER_RECIPIENT', 'EXIT_CHECKLIST_COMPLETED', 'EXIT_CHECKLIST_COMPLETION', 'EXIT_CHECKLIST_PDF', 'EMPLOYEE_CHANGE_INFO', 'EMPLOYEE_CHANGE_SUMMARY', 'MANUAL_EMAIL', 'SYSTEM_NOTIFICATION', 'GENERIC_EMAIL', 'MENTOR_ASSIGNED') NOT NULL;

-- AlterTable
ALTER TABLE `OffboardingChangeLog` MODIFY `action` ENUM('CREATED', 'UPDATED', 'DELETED', 'RESTORED', 'REVERTED', 'CANCELLED', 'MAIL_SENT', 'MAIL_ENQUEUED', 'MAIL_FAILED', 'STATUS_CHANGED', 'PROBATION_REMINDER_SENT', 'PROBATION_EVALUATION_SENT', 'NOTICE_REMINDER_SENT', 'OFFICIAL_CHANGE_APPLIED') NOT NULL;

-- AlterTable
ALTER TABLE `OnboardingChangeLog` MODIFY `action` ENUM('CREATED', 'UPDATED', 'DELETED', 'RESTORED', 'REVERTED', 'CANCELLED', 'MAIL_SENT', 'MAIL_ENQUEUED', 'MAIL_FAILED', 'STATUS_CHANGED', 'PROBATION_REMINDER_SENT', 'PROBATION_EVALUATION_SENT', 'NOTICE_REMINDER_SENT', 'OFFICIAL_CHANGE_APPLIED') NOT NULL;

-- AlterTable
ALTER TABLE `mail_jobs` MODIFY `type` ENUM('EMPLOYEE_INFO', 'MONTHLY_SUMMARY', 'PROBATION_WARNING', 'PROBATION_REMINDER', 'PROBATION_ENDING', 'PROBATION_EVALUATION_LINK', 'PROBATION_MISSING_EMAIL', 'PROBATION_SUBMITTED', 'PROBATION_FORM_COMPLETED', 'PROBATION_SUPERVISOR_21_DAYS', 'PROBATION_HR_INFO_21_DAYS', 'PROBATION_HR_REMINDER_1_DAY', 'PROBATION_COMPLETED', 'PROBATION_MISSING_SUPERVISOR', 'NOTICE_WARNING', 'NOTICE_ENDING', 'SIGNATURE_INVITE', 'EXIT_CHECKLIST_SIGNATURE_INVITE', 'EXIT_SIGNATURE_INVITE', 'BEHALF_SIGNATURE_INVITE', 'EXIT_CHECKLIST_BEHALF_SIGNATURE', 'HANDOVER_RECIPIENT', 'HANDOVER_RECIPIENT_INFO', 'EXIT_CHECKLIST_HANDOVER_RECIPIENT', 'EXIT_CHECKLIST_COMPLETED', 'EXIT_CHECKLIST_COMPLETION', 'EXIT_CHECKLIST_PDF', 'EMPLOYEE_CHANGE_INFO', 'EMPLOYEE_CHANGE_SUMMARY', 'MANUAL_EMAIL', 'SYSTEM_NOTIFICATION', 'GENERIC_EMAIL', 'MENTOR_ASSIGNED') NOT NULL;

-- CreateTable
CREATE TABLE `EmployeeChange` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` ENUM('POSITION', 'NAME') NOT NULL,
    `status` ENUM('DRAFT', 'APPLIED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
    `audience` ENUM('ONBOARDING_GROUP', 'ALL_EMPLOYEES', 'HR_GROUP') NULL,
    `effectiveDate` DATETIME(3) NOT NULL,
    `titleBefore` VARCHAR(191) NULL,
    `name` VARCHAR(191) NOT NULL,
    `surname` VARCHAR(191) NOT NULL,
    `titleAfter` VARCHAR(191) NULL,
    `personalNumber` VARCHAR(191) NULL,
    `oldSurname` VARCHAR(191) NULL,
    `newSurname` VARCHAR(191) NULL,
    `oldDepartment` VARCHAR(191) NULL,
    `newDepartment` VARCHAR(191) NULL,
    `oldUnitName` VARCHAR(191) NULL,
    `newUnitName` VARCHAR(191) NULL,
    `oldPositionName` VARCHAR(191) NULL,
    `newPositionName` VARCHAR(191) NULL,
    `oldPositionNum` VARCHAR(191) NULL,
    `newPositionNum` VARCHAR(191) NULL,
    `notes` TEXT NULL,
    `appliedAt` DATETIME(3) NULL,
    `appliedBy` VARCHAR(191) NULL,
    `emailSentAt` DATETIME(3) NULL,
    `emailSentBy` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,
    `deletedBy` VARCHAR(191) NULL,
    `deleteReason` VARCHAR(191) NULL,

    INDEX `EmployeeChange_type_idx`(`type`),
    INDEX `EmployeeChange_status_idx`(`status`),
    INDEX `EmployeeChange_audience_idx`(`audience`),
    INDEX `EmployeeChange_effectiveDate_idx`(`effectiveDate`),
    INDEX `EmployeeChange_personalNumber_idx`(`personalNumber`),
    INDEX `EmployeeChange_deletedAt_idx`(`deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EmployeeChangeTarget` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `changeId` INTEGER NOT NULL,
    `targetType` ENUM('ONBOARDING', 'OFFBOARDING') NOT NULL,
    `targetId` INTEGER NOT NULL,
    `oldValues` JSON NOT NULL,
    `newValues` JSON NOT NULL,
    `appliedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `appliedBy` VARCHAR(191) NOT NULL,

    INDEX `EmployeeChangeTarget_changeId_idx`(`changeId`),
    INDEX `EmployeeChangeTarget_targetType_targetId_idx`(`targetType`, `targetId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `EmailHistory_changeId_idx` ON `EmailHistory`(`changeId`);

-- AddForeignKey
ALTER TABLE `EmployeeChangeTarget` ADD CONSTRAINT `EmployeeChangeTarget_changeId_fkey` FOREIGN KEY (`changeId`) REFERENCES `EmployeeChange`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `EmailHistory` ADD CONSTRAINT `EmailHistory_changeId_fkey` FOREIGN KEY (`changeId`) REFERENCES `EmployeeChange`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
