-- AlterTable
ALTER TABLE `ExitChecklistEvent` MODIFY `action` ENUM('LOCKED', 'UNLOCKED', 'UPDATED', 'ITEM_SIGNED', 'ITEM_SIGNATURE_CLEARED', 'ASSET_ADDED', 'ASSET_UPDATED', 'ASSET_REMOVED', 'SIGNATURE_INVITE_SENT', 'HANDOVER_RECIPIENT_INVITE_SENT', 'PDF_DOWNLOADED', 'EMAIL_FAILED', 'DEADLINE_REMINDER_SENT') NOT NULL;
