-- AlterTable
ALTER TABLE `EmploymentDocumentEvent` MODIFY `action` ENUM('CREATED', 'SENT', 'PDF_SENT', 'FILLED', 'EDITED', 'LOCKED', 'UNLOCKED', 'RESET', 'REGENERATED', 'PDF_DOWNLOADED', 'EMAIL_FAILED') NOT NULL;
