-- CreateTable
CREATE TABLE `MailQueue` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` ENUM('IT', 'FACILITY', 'HR', 'TRAINING', 'CANDIDATE', 'ALL') NOT NULL,
    `employeeIds` JSON NOT NULL,
    `sendAt` DATETIME(3) NOT NULL,
    `status` ENUM('QUEUED', 'SENT', 'FAILED') NOT NULL DEFAULT 'QUEUED',
    `createdBy` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `sentAt` DATETIME(3) NULL,
    `error` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
