-- AlterTable
ALTER TABLE `EmailHistory` MODIFY `emailType` ENUM('EMPLOYEE_INFO', 'MONTHLY_SUMMARY', 'PROBATION_EVALUATION_INVITE', 'PROBATION_EVALUATION_REMINDER', 'PROBATION_EVALUATION_HR_INFO', 'PROBATION_EVALUATION_HR_MISSING_SUPERVISOR', 'PROBATION_EVALUATION_HR_NOT_COMPLETED', 'PROBATION_EVALUATION_COMPLETED', 'NOTICE_WARNING', 'NOTICE_ENDING', 'SIGNATURE_INVITE', 'EXIT_CHECKLIST_SIGNATURE_INVITE', 'EXIT_SIGNATURE_INVITE', 'BEHALF_SIGNATURE_INVITE', 'EXIT_CHECKLIST_BEHALF_SIGNATURE', 'HANDOVER_RECIPIENT', 'HANDOVER_RECIPIENT_INFO', 'EXIT_CHECKLIST_HANDOVER_RECIPIENT', 'EXIT_CHECKLIST_COMPLETED', 'EXIT_CHECKLIST_COMPLETION', 'EXIT_CHECKLIST_PDF', 'EMPLOYEE_CHANGE_INFO', 'EMPLOYEE_CHANGE_SUMMARY', 'MANUAL_EMAIL', 'SYSTEM_NOTIFICATION', 'GENERIC_EMAIL', 'MENTOR_ASSIGNED', 'STATISTICS_REPORT') NOT NULL;

-- AlterTable
ALTER TABLE `mail_jobs` MODIFY `type` ENUM('EMPLOYEE_INFO', 'MONTHLY_SUMMARY', 'PROBATION_EVALUATION_INVITE', 'PROBATION_EVALUATION_REMINDER', 'PROBATION_EVALUATION_HR_INFO', 'PROBATION_EVALUATION_HR_MISSING_SUPERVISOR', 'PROBATION_EVALUATION_HR_NOT_COMPLETED', 'PROBATION_EVALUATION_COMPLETED', 'NOTICE_WARNING', 'NOTICE_ENDING', 'SIGNATURE_INVITE', 'EXIT_CHECKLIST_SIGNATURE_INVITE', 'EXIT_SIGNATURE_INVITE', 'BEHALF_SIGNATURE_INVITE', 'EXIT_CHECKLIST_BEHALF_SIGNATURE', 'HANDOVER_RECIPIENT', 'HANDOVER_RECIPIENT_INFO', 'EXIT_CHECKLIST_HANDOVER_RECIPIENT', 'EXIT_CHECKLIST_COMPLETED', 'EXIT_CHECKLIST_COMPLETION', 'EXIT_CHECKLIST_PDF', 'EMPLOYEE_CHANGE_INFO', 'EMPLOYEE_CHANGE_SUMMARY', 'MANUAL_EMAIL', 'SYSTEM_NOTIFICATION', 'GENERIC_EMAIL', 'MENTOR_ASSIGNED', 'STATISTICS_REPORT') NOT NULL;

-- CreateTable
CREATE TABLE `statistics_saved_views` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `metric` VARCHAR(191) NOT NULL,
    `dimension` VARCHAR(191) NOT NULL,
    `displayType` VARCHAR(191) NOT NULL,
    `filters` JSON NOT NULL,
    `createdBy` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
