-- AlterTable
ALTER TABLE `ProbationEvaluationRequest` ADD COLUMN `tajemnikRequired` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `ProbationEvaluationRequestEvent` MODIFY `action` ENUM('CREATED', 'UPDATED', 'INVITE_QUEUED', 'INVITE_SENT', 'REMINDER_QUEUED', 'REMINDER_SENT', 'HR_INFO_QUEUED', 'HR_INFO_SENT', 'HR_REMINDER_QUEUED', 'HR_REMINDER_SENT', 'MISSING_SUPERVISOR', 'COMPLETED', 'EDITED', 'RESET', 'LOCKED', 'UNLOCKED', 'TOKEN_REGENERATED', 'CANCELLED', 'EXPIRED', 'EMAIL_FAILED', 'PDF_DOWNLOADED', 'UNLOCK_REMINDER_QUEUED', 'UNLOCK_REMINDER_SENT', 'TAJEMNIK_REVIEW_SENT', 'TAJEMNIK_REVIEWED') NOT NULL;
