-- CreateTable
CREATE TABLE `ReportAccessLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reportType` ENUM('EMPLOYEE_INFO', 'MONTHLY_SUMMARY', 'PROBATION_EVALUATION_INVITE', 'PROBATION_EVALUATION_REMINDER', 'PROBATION_EVALUATION_HR_INFO', 'PROBATION_EVALUATION_HR_MISSING_SUPERVISOR', 'PROBATION_EVALUATION_HR_NOT_COMPLETED', 'PROBATION_EVALUATION_COMPLETED', 'NOTICE_WARNING', 'NOTICE_ENDING', 'SIGNATURE_INVITE', 'EXIT_CHECKLIST_SIGNATURE_INVITE', 'EXIT_SIGNATURE_INVITE', 'BEHALF_SIGNATURE_INVITE', 'EXIT_CHECKLIST_BEHALF_SIGNATURE', 'HANDOVER_RECIPIENT', 'HANDOVER_RECIPIENT_INFO', 'EXIT_CHECKLIST_HANDOVER_RECIPIENT', 'EXIT_CHECKLIST_COMPLETED', 'EXIT_CHECKLIST_COMPLETION', 'EXIT_CHECKLIST_PDF', 'EMPLOYEE_CHANGE_INFO', 'EMPLOYEE_CHANGE_SUMMARY', 'MANUAL_EMAIL', 'SYSTEM_NOTIFICATION', 'GENERIC_EMAIL', 'MENTOR_ASSIGNED', 'STATISTICS_REPORT') NOT NULL,
    `by` VARCHAR(191) NULL,
    `byName` VARCHAR(191) NULL,
    `byEmail` VARCHAR(191) NULL,
    `message` TEXT NULL,
    `meta` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `ReportAccessLog_reportType_idx`(`reportType`),
    INDEX `ReportAccessLog_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `UserAuditLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `targetUserId` VARCHAR(191) NULL,
    `targetEmail` VARCHAR(191) NOT NULL,
    `action` ENUM('CREATED', 'ROLE_CHANGED', 'REMOVED', 'DEMOTED') NOT NULL,
    `oldValue` VARCHAR(191) NULL,
    `newValue` VARCHAR(191) NULL,
    `by` VARCHAR(191) NULL,
    `byName` VARCHAR(191) NULL,
    `byEmail` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `UserAuditLog_targetUserId_idx`(`targetUserId`),
    INDEX `UserAuditLog_action_idx`(`action`),
    INDEX `UserAuditLog_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
